// <auto-generated />
namespace SmartAdminMvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class EmpresasInternos6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EmpresasInternos6));
        
        string IMigrationMetadata.Id
        {
            get { return "201610272311452_EmpresasInternos6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
